# Generated by Django 4.0.8 on 2023-01-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='User',
        ),
    ]
